"""
Autogenerated based on '${template_path}'
and list of available models.
Do not modify this autogenerated code. Instead modify template.
"""
from .base import SimGroup, create_multi_sim_group

% for model in models:
from .${model.lower()} import ${model}SimGroup
% endfor

__all__ = [
    'SimGroup',
% for model in models:
    '${model}SimGroup',
% endfor
]