# Autogenerated using:
# - Template: 'src/cubnm/sim/simgroup.py.mako'
# - Model definition: 'codegen/recipes/rjr.yaml'
# Do not modify this autogenerated code. Instead modify template
# or model definition.
from .base import SimGroup
import sys
import logging
import numpy as np

logging.basicConfig(stream=sys.stdout, level=logging.WARNING)
logger = logging.getLogger(__name__)

class rJRSimGroup(SimGroup):
    model_name = "rJR"
    global_param_names = ['G']
    regional_param_names = ['C_EI', 'C_IE', 'R', 'sigma']
    state_names = ['EPSP', 'IPSP', 'EPSC', 'IPSC', 'normEPSP']
    sel_state_var = "normEPSP"
    n_noise = 1
    default_params = {
        "G": None,  # required
        "C_EI": 6.0,
        "C_IE": 6.0,
        "R": 2.2,
        "sigma": 1625.0,
    }

    def __init__(
        self, 
        *args, 
        R_mean = 2.2, 
        R_range = 0.0, 
        R_dist_uniform = True, 
        **kwargs
    ):
        r"""
        Group of reduced Jansen-Rit simulations that are executed in parallel.

        Parameters
        ---------
        R_mean: :obj:`float`
            mean of the natural frequency distribution
        R_range: :obj:`float`
            range of the natural frequency distribution
        R_dist_uniform: :obj:`bool`
            whether distribution of natural frequencies is uniform rather than normal
        *args, **kwargs:
            see :class:`cubnm.sim.SimGroup` for details

        Attributes
        ----------
        param_lists: :obj:`dict` of :obj:`np.ndarray`
            dictionary of parameter lists, including
                - ``'G'``: global coupling strength. Shape: (N_SIMS,)
                - ``'C_EI'``: local E to I coupling. Shape: (N_SIMS, nodes)
                - ``'C_IE'``: local I to E coupling. Shape: (N_SIMS, nodes)
                - ``'R'``: local natural frequency. Shape: (N_SIMS, nodes)
                - ``'sigma'``: noise strength. Shape: (N_SIMS, nodes)
                - ``'v'``: conduction velocity. Shape: (N_SIMS,)
        """
        self.R_mean = R_mean
        self.R_range = R_range
        self.R_dist_uniform = R_dist_uniform
        # parent init must be called after setting
        # model-specific attributes because
        # it sets .last_config which may include some
        # model-specific attributes
        super().__init__(*args, **kwargs)

    def get_config(self, *args, **kwargs):
        config = super().get_config(*args, **kwargs)
        config.update({
            'R_mean': self.R_mean,
            'R_range': self.R_range,
            'R_dist_uniform': self.R_dist_uniform,
        })
        return config
    
    @property
    def _model_config(self):
        """
        Internal model configuration used in the simulation
        """
        model_config = super()._model_config
        model_config.update({
            'R_mean': str(self.R_mean),
            'R_range': str(self.R_range),
            'R_dist_uniform': str(int(self.R_dist_uniform)),
        })
        return model_config

    @SimGroup.N.setter
    def N(self, N):
        super(rJRSimGroup, rJRSimGroup).N.__set__(self, N)
        if self.R_dist_uniform:
            # sample from uniform distribution
            # repeat it across simulations
            # use the same random seed as the simulation noise
            rng = np.random.default_rng(self.sim_seed)
            # TODO: with certain R_range and R_mean some nodes may
            # have negative R values. Fix this!
            self.param_lists["R"] = np.tile(
                (rng.uniform(-1, 1, self.nodes) * self.R_range + 1) * self.R_mean, 
                (self._N, 1)
            )
        else:
            # TODO
            raise NotImplementedError
